#!/bin/bash

# Docs
# 1. Purpose to replace usage of xev which didn't give the MSC_SCAN values.
# 2. Usage:
#     sudo evtest # list all input devices
#     sudo evtest /dev/input/eventX # replace X with result from above


installer_name="evtest"
installer_description="installs evtest"
installer_link="https://archlinux.org/packages/extra/x86_64/evtest/"

SHORT_PKG="evtest"
LONG_PKG="extra/${SHORT_PKG}"

inst_is_installed() {
    is_pacman_installed ${SHORT_PKG} 
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install ${LONG_PKG}
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_can_upgrade() {
    return 1
}

inst_upgrade() {
    return 1
}

inst_uninstall() {
    pacman_uninstall ${SHORT_PKG}
}
