#!/bin/sh

installer_name="dosfstools"
installer_description="Installs dosfstools."
installer_link="https://archlinux.org/packages/core/x86_64/dosfstools/"

pacman_pkg="core/dosfstools"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "fsck.fat -n /dev/DEVICE"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
