#!/bin/sh

installer_name="rsync"
installer_description="Installs rsync."
installer_link="https://archlinux.org/packages/extra/x86_64/rsync/"

pacman_pkg="extra/rsync"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Sync between two directories on the local machine"
    htext "rsync -av dir1/ dir2/"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
