#!/bin/sh
set -e
set -u

installer_name="libinputtools"
installer_description="Installs libinput-tools. Purpose to list devices to allow config of touchpad."
installer_link="https://archlinux.org/packages/extra/x86_64/libinput-tools/"

pacman_pkg="extra/libinput-tools"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "libinput"
    hexamples
    htext "List devices"
    htext "libinput list-devices"
    htext
    htext "Get device info"
    htext "udevadm info DEVICE"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    is_pacman_installed "${pacman_pkg}"
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
