#!/bin/sh
set -e
set -u

installer_name="qpdf"
installer_description="Installs qpdf."
installer_link="https://archlinux.org/packages/extra/x86_64/qpdf/"

pacman_pkg="extra/qpdf"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Concatenate pdf:s (the following two examples are equivalent)"
    htext "qpdf doc1.pdf --pages . doc2.pdf doc3.pdf -- out.pdf"
    htext "qpdf doc1.pdf --pages doc1.pdf doc2.pdf doc3.pdf -- out.pdf"
    hseealso
    htext "${installer_link}"
    htext "https://qpdf.readthedocs.io"
}

inst_is_installed() {
    is_pacman_installed "${pacman_pkg}"
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
