#!/bin/sh

installer_name="nuphykeyboard"
installer_description="Explains how to configure the nuphy halo v2 keyboard."
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "See install manual"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
    htext
    htext "Nuphy VIA usage guide"
    htext "https://nuphy.com/pages/via-usage-guide-for-nuphy-keyboards"
    htext
    htext "Nuphy keyboard JSON files"
    htext "https://nuphy.com/pages/json-files-for-nuphy-keyboards"
    htext
    htext "QMK keycodes"
    htext "https://docs.qmk.fm/keycodes"
}

inst_is_installed() {
    return 0
}

inst_can_install() {
    return 1
}

inst_install() {
    return 0
}

inst_can_install_manual() {
    return 0
}

inst_install_manual() {
    echo "Check the brave device log if issues occur"
    echo "brave://device-log"
    echo ""
    echo "1. Enable File System Access API in brave"
    echo "brave://flags/#file-system-access-api"
    echo ""
    echo "2. Configure udev rule"
    echo "2.1. Create /etc/udev/rules.d/99-via.rules"
    echo '2.2. KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0666", TAG+="uaccess", TAG+="udev-acl"'
    echo "2.3. sudo udevadm control --reload-rules"
    echo "2.4. sudo udevadm trigger"
    echo ""
    echo "3. Upload the keyboard layout"
    echo "3.1. Go to https://usevia.app"
    echo "3.2. Upload the file config/nuphy-halo75-v2-via.json"
    return 0
}

inst_uninstall() {
    return 0
}
