#!/bin/sh
set -e
set -u

installer_name="docs_keybinds_ghostty"
installer_description="Ghostty keybindings documentation."
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Fullscreen"
    htext "<C-CR>"
    htext
    htext "Toggle inspector"
    htext "<C-S-i>"
    htext
    htext "Change font size"
    htext "<C-+>"
    htext "<C-->"
    htext
    htext "Create and change tabs"
    htext "<C-S-t>"
    htext "<C-Tab>"
    htext
    htext "Open splits right and bottom"
    htext "<C-S-o>"
    htext "<C-S-e>"
    htext
    htext "Close a tab or split"
    htext "<C-S-w>"
    htext
    htext "Move between splits"
    htext "<C-A-Up>"
    htext "<C-A-Down>"
    htext "<C-A-Left>"
    htext "<C-A-Right>"
    htext
    htext "DESCRIPTION"
    htext "KEYBIND"
    htext
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    return 0
}
