#!/bin/sh

installer_name="fastfetch"
installer_description="Installs fastfetch. Used to display system statistics."
installer_link="https://archlinux.org/packages/extra/x86_64/fastfetch/"

pacman_pkg="extra/fastfetch"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "fastfetch"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
    htext "https://github.com/fastfetch-cli/fastfetch"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
