#!/bin/bash

# =====================================================================================
# ============================== program installer utils ==============================
# =====================================================================================

htitle() {
    printf "%25s%s\n" "" "${1}"
}

hdesc() {
    printf "\nDESCRIPTION\n"
}

husage() {
    printf "\nUSAGE\n"
}

hexamples() {
    printf "\nEXAMPLES\n"
}

hseealso() {
    printf "\nSEE ALSO\n"
}

htext() {
    printf "%4s%s\n" "" "${1}"
}

is_command() {
    if command -v "${1}" >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

mv_log() {
    arg_src="${1}"
    arg_dst="${2}"
    
    echo "mv ${arg_src} ${arg_dst}"
    mv ${arg_file} ${bak_file}
    return 0
}

mv_bak() {
    arg_file="${1}"

    if [ ! -f "${arg_file}" ]; then
        return 0
    fi
    
    bak_file="${arg_file}.$(date +%Y%m%d_%H%M%S).bak"

    mv_log ${arg_file} ${bak_file}
    return 0
}

cp_log() {
    arg_src="${1}"
    arg_dst="${2}"

    echo "cp ${arg_src} ${arg_dst}"
    cp ${arg_src} ${arg_dst}
}

cp_bak() {
    arg_src="${1}"
    arg_dst="${2}"

    mv_bak ${arg_dst}

    cp_log ${arg_src} ${arg_dst}
}

is_pacman_installed() {
    if pacman -Qe "${1}" >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

pacman_install() {
    arg_pkg="${1}"

    if ! is_command pacman; then
        echo "pacman does not exist"
        exit 1
    fi

    short_pkg=$(long_to_short_pkg "${arg_pkg}")

    if pacman -Qd "${short_pkg}" 1>/dev/null 2>&1; then
        echo "marking dependency as explicitly installed: ${arg_pkg} - ${short_pkg}"
        sudo pacman -D --asexplicit "${short_pkg}"
        return 0
    fi

    if pacman -Qe "${short_pkg}" 1>/dev/null 2>&1; then
        echo "already installed: ${arg_pkg} - ${short_pkg}"
        return 0
    fi

    echo "installing: ${arg_pkg} - ${short_pkg}"

    sudo pacman --noconfirm -S "${1}"
}

pacman_uninstall() {
    arg_pkg="${1}"

    if ! is_command pacman; then
        echo "pacman does not exist"
        exit 1
    fi

    short_pkg=$(long_to_short_pkg "${arg_pkg}")

    sudo pacman --noconfirm -R ${short_pkg}
}

# =============================================================================
# ============================== installer utils ==============================
# =============================================================================

long_to_short_pkg() {
    arg_string="${1}"
    split_last=$(echo "${arg_string}" | tr "/" "\n" | tail -n 1)
    echo "${split_last}"
}

describe_installer() {
    echo -e "\033[1m${installer_name}\033[0m - ${installer_description}"
    echo "| link: ${installer_link}"
}

prog_inst_name=""

source_installer() {
    prog_inst_name="${1}"
    source ${prog_inst_name}
}

pacman_upgrade() {
    if ! is_command pacman; then
        echo "pacman does not exist"
        exit 1
    fi

    sudo pacman --noconfirm -Syu
    sudo pacman --noconfirm -Fy
}
