#!/bin/sh
set -e
set -u

installer_name="tokei"
installer_description="Installs tokei. Used to count lines of code."
installer_link="https://archlinux.org/packages/extra/x86_64/tokei/"

pacman_pkg="extra/tokei"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "tokei DIR"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    is_pacman_installed "${pacman_pkg}"
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
