#!/bin/bash

# Docs
# N/A

installer_name="bashrc"
installer_description="installs bashrc and bash_profile"
installer_link="n/a"


inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    bashrc_dest="${HOME}/.bashrc"
    bashprofile_dest="${HOME}/.bash_profile"

    echo "copying bashrc into ${bashrc_dest}"
    cp config/bashrc ${bashrc_dest}

    echo "copying bashprofile into ${bashprofile_dest}"
    cp config/bash_profile ${bashprofile_dest}

    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_can_upgrade() {
    return 1
}

inst_upgrade() {
    return 1
}

inst_uninstall() {
    return 0
}
