#!/bin/bash

installer_name="NAME"
installer_description="THIS_IS_THE_DESCRIPTION"
installer_link="httpsomething"


inst_is_installed() {

    return 0
}

inst_can_install() {

    return 0
}

inst_install() {
    echo "installing..."

    return 0
}

inst_can_install_manual() {

    return 1
}

inst_install_manual() {
    echo "1. copy file to somewhere"
    echo "2. then do this"
    echo "3. also open application and do this"

    return 0
}

inst_can_upgrade() {
    return 1
}

inst_upgrade() {
    return 1
}

inst_uninstall() {
    echo "uninstalling..."

    return 0
}
