#!/bin/sh

installer_name="tealdeer"
installer_description="Installs tealdeer, simplified man pages."
installer_link="https://archlinux.org/packages/extra/x86_64/tealdeer/"

pacman_pkg="extra/tealdeer"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "tldr PAGE"
    hexamples
    htext "Show a tldr page"
    htext "tldr feh"
    htext
    htext "Update the local cache"
    htext "tldr --update"
    htext
    htext "Clear the local cache"
    htext "tldr --clear-cache"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
