#!/bin/sh

installer_name="kdesettings"
installer_description="Configures kde settings such as natural scrolling."
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "systemsettings"
    hexamples
    htext "View modules in systemsetting"
    htext "systemsettings --list"
    htext
    htext "Open a specific module like kcm_touchpad"
    htext "systemsettings kcm_touchpad"
    htext
    htext "View input device properties"
    htext "busctl --user introspect org.kde.KWin /org/kde/KWin/InputDevice/event11 org.kde.KWin.InputDevice"
    htext
    htext "View all locales"
    htext "locale --all-locales"
    hseealso
    htext "${installer_link}"
    htext "kciminputrc file"
    htext "Created in .config/kcminputrc after a setting is modified."
    htext
    htext "https://discuss.kde.org/t/ambidextrous-how-to-write-a-script-to-switch-mouse-buttons/38494"
    htext "https://discuss.kde.org/t/changing-mouse-buttonrebinds-for-extrabuttons-programmatically-kcminputrc/42174"
    htext "https://www.reddit.com/r/kde/comments/1odxxhg/any_documentation_for_editing_kcminputrc/"
    htext "https://discuss.kde.org/t/how-to-change-settings-through-command-line/41361"
    htext
    htext "Locale"
    htext "https://wiki.archlinux.org/title/Locale#Generating_locales"
    htext
    htext "[HowTo] Use multiple languages in KDE Plasma"
    htext "https://forum.manjaro.org/t/howto-use-multiple-languages-in-kde-plasma/150503"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    if ! is_command libinput; then
        echo "missing libinput"
        return 1
    fi

    if ! is_command udevadm; then
        echo "missing udevadm"
        return 1
    fi

    return 0
}

set_inputdevice_prop() {
    arg_dev_path="${1}"
    arg_prop="${2}"
    arg_type="${3}"
    arg_val="${4}"

    dev_name=$(udevadm info "${arg_dev_path}" | grep "M:" | tr -d "M: ")
    if [ "/dev/input/${dev_name}" != "${arg_dev_path}" ]; then
        echo "failed to find device name from ${arg_dev_path} got: ${dev_name}"
        return 1
    fi

    val_before=$(busctl --user get-property org.kde.KWin "/org/kde/KWin/InputDevice/${dev_name}" org.kde.KWin.InputDevice "${arg_prop}")
    busctl --user set-property org.kde.KWin "/org/kde/KWin/InputDevice/${dev_name}" org.kde.KWin.InputDevice "${arg_prop}" "${arg_type}" "${arg_val}"
    val_after=$(busctl --user get-property org.kde.KWin "/org/kde/KWin/InputDevice/${dev_name}" org.kde.KWin.InputDevice "${arg_prop}")

    echo "set input device property"
    echo "dev path:    ${arg_dev_path}"
    echo "dev name:    ${dev_name}"
    echo "property:    ${arg_prop}"
    echo "before:      ${val_before}"
    echo "after:       ${val_after}"
}

config_touchpad() {
    echo "configuring touchpad: libinput list-devices will be called with sudo"

    dev_substring="Touchpad"
    num_substring_lines=$(sudo libinput list-devices | grep -c "${dev_substring}")
    if [ "${num_substring_lines}" -ne "1" ]; then
        echo "too many ${dev_substring} results expected 1 got ${num_substring_lines}"
        return 0
    fi

    dev_path=$(sudo libinput list-devices | grep "${dev_substring}" -A 1 | tail -n 1 | tr -s " " "\n" | tail -n 1)

    set_inputdevice_prop "${dev_path}" naturalScroll b true
}

inst_install() {
    config_touchpad

    # systemsettings kcm_smserver
    kwriteconfig6 --file ksmserverrc --group General --key loginMode emptySession

    # systemsettings kcm_screenlocker
    # Lock screen automatically in minutes
    kwriteconfig6 --file kscreenlockerrc --group Daemon --key Timeout "45"
    # Lock after waking from sleep
    kwriteconfig6 --file kscreenlockerrc --group Daemon --key LockOnResume "true"
    # Delay before password required in seconds
    kwriteconfig6 --file kscreenlockerrc --group Daemon --key LockGrace "0"

    # systemsettings kcm_powerdevilprofilesconfig
    # When inactive: sleep
    kwriteconfig6 --file powerdevilrc --group AC --group SuspendAndShutdown --key AutoSuspendAction --delete
    # After X minutes in seconds
    kwriteconfig6 --file powerdevilrc --group AC --group SuspendAndShutdown --key AutoSuspendIdleTimeoutSec "$((60 * 30))"

    # see /etc/locale.gen
    # https://wiki.archlinux.org/title/Locale#Generating_locales

    en_loc_result="$(sudo sed -n "s|#en_US|en_US|p" /etc/locale.gen)"
    if [ "${en_loc_result}" != "" ]; then
        sudo sed -i "s|#en_US|en_US|" /etc/locale.gen
        sudo locale-gen
    fi

    sv_loc_result="$(sudo sed -n "s|#sv_SE|sv_SE|p" /etc/locale.gen)"
    if [ "${sv_loc_result}" != "" ]; then
        sudo sed -i "s|#sv_SE|sv_SE|" /etc/locale.gen
        sudo locale-gen
    fi

    dk_loc_result="$(sudo sed -n "s|#en_DK|en_DK|p" /etc/locale.gen)"
    if [ "${dk_loc_result}" != "" ]; then
        sudo sed -i "s|#en_DK|en_DK|" /etc/locale.gen
        sudo locale-gen
    fi
    # See /etc/vconsole.conf
    localectl --no-convert set-x11-keymap us,se pc105 "" "grp:alt_shift_toggle,compose:ralt"

    # systemsettings kcm_regionandlang
    loc_c="C.UTF-8"
    loc_en_us="en_US.UTF-8"
    # loc_sv_se="sv_SE.UTF-8"
    # loc_en_dk="en_DK.UTF-8"
    v_lang="${loc_en_us}"
    v_numeric="${loc_c}"
    v_time="${loc_c}"
    v_monetary="${loc_c}"
    v_measurement="${loc_c}"
    v_paper="${loc_c}"
    v_address="${loc_c}"
    v_name="${loc_c}"
    v_telephone="${loc_c}"
    sudo localectl set-locale LANG="${v_lang}"
    kwriteconfig6 --file plasma-localerc --group Formats --key LANG "${v_lang}"
    sudo localectl set-locale LC_NUMERIC="${v_numeric}"
    kwriteconfig6 --file plasma-localerc --group Formats --key LC_NUMERIC "${v_numeric}"
    # Special case which differs for KDE/Qt applications and glibc.
    sudo localectl set-locale LC_TIME="${v_time}"
    kwriteconfig6 --file plasma-localerc --group Formats --key LC_TIME "en_SE.UTF-8"
    sudo localectl set-locale LC_MONETARY="${v_monetary}"
    kwriteconfig6 --file plasma-localerc --group Formats --key LC_MONETARY "${v_monetary}"
    sudo localectl set-locale LC_MEASUREMENT="${v_measurement}"
    kwriteconfig6 --file plasma-localerc --group Formats --key LC_MEASUREMENT "${v_measurement}"
    sudo localectl set-locale LC_PAPER="${v_paper}"
    kwriteconfig6 --file plasma-localerc --group Formats --key LC_PAPER "${v_paper}"
    sudo localectl set-locale LC_ADDRESS="${v_address}"
    kwriteconfig6 --file plasma-localerc --group Formats --key LC_ADDRESS "${v_address}"
    sudo localectl set-locale LC_NAME="${v_name}"
    kwriteconfig6 --file plasma-localerc --group Formats --key LC_NAME "${v_name}"
    sudo localectl set-locale LC_TELEPHONE="${v_telephone}"
    kwriteconfig6 --file plasma-localerc --group Formats --key LC_TELEPHONE "${v_telephone}"

    kwriteconfig6 --file kdeglobals --group Locale --key BinaryUnitDialect "0"

    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    return 0
}
