#!/bin/sh

installer_name="ytdlp"
installer_description="Installs yt-dlp."
installer_link="https://archlinux.org/packages/extra/any/yt-dlp/"

pacman_pkg="extra/yt-dlp"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "yt-dlp URL"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
    htext "https://wiki.archlinux.org/title/Yt-dlp"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
