#!/bin/sh

installer_name="figlet"
installer_description="Installs figlet. Create big ascii letters."
installer_link="https://archlinux.org/packages/extra/x86_64/figlet/"

pacman_pkg="extra/figlet"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "figlet"
    hexamples
    htext "Centered text using terminal width (not 80 chars) and not combining characters"
    htext "figlet hello -c -t -k"
    htext
    htext "Find all available fonts"
    htext "pacman -Ql figlet | grep \"\.flf$\""
    htext
    htext "Use a different font"
    htext "figlet hello -f digital"
    htext
    hseealso
    htext "${installer_link}"
    htext "https://www.figlet.org/"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
