#!/bin/sh

installer_name="shellcheck"
installer_description="Installs shellcheck to validate shell scripts."
installer_link="https://archlinux.org/packages/extra/x86_64/shellcheck/"

pacman_pkg="extra/shellcheck"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "shellcheck FILE"
    hexamples
    htext "Check POSIX sh"
    htext "shellcheck -s sh FILE"
    htext
    htext "Check POSIX sh with maximal strictness"
    htext "shellcheck --severity style --enable all -s sh FILE"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
