#!/bin/bash

# https://archlinux.org/packages/extra/x86_64/git/

declare MAIL="ludvig.westerdahl.tech.v1@protonmail.com"
if [[ "${1}" != "" ]]; then
    MAIL="${1}"
fi

declare NAME="ludvig"
if [[ "${2}" != "" ]]; then
    NAME="${2}"
fi

declare EDITOR="vim"
if [[ "${3}" != "" ]]; then
    EDITOR="${3}"
fi

sudo pacman --noconfirm -S extra/git

git config --global user.email "${MAIL}"
git config --global user.name "${NAME}"
git config --global core.editor "${EDITOR}"
