#!/bin/bash

installer_name="archwallpaper"
installer_description="Installs archlinux-wallpaper and configures it."
installer_link="https://archlinux.org/packages/extra/any/archlinux-wallpaper/"

pacman_pkg="extra/archlinux-wallpaper"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "List installed and available wallpapers"
    htext "ls -1 /usr/share/backgrounds/archlinux"
    hseealso
    htext "${installer_link}"
    htext "https://bbs.archlinux.org/viewtopic.php?id=259604"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    if ! is_pacman_installed ${pacman_pkg}; then
        pacman_install ${pacman_pkg}
    fi

    wallpaper_img="/usr/share/backgrounds/archlinux/conference.png"
    lockscreen_img="/usr/share/backgrounds/archlinux/simple.png"


    plasma-apply-wallpaperimage ${wallpaper_img}

    kwriteconfig6 --file kscreenlockerrc --group Greeter --group Wallpaper --group org.kde.image --group General --key Image "file://${lockscreen_img}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall ${pacman_pkg}
}
