#!/bin/sh

installer_name="vim"
installer_description="Installs vim."
installer_link="https://archlinux.org/packages/extra/x86_64/vim/"

pacman_pkg="extra/vim"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Show binary content of a compiled binary excluding NULL rows"
    htext "xxd -a a.out"
    hseealso
    htext "${installer_link}"
    htext
    htext "It also provides xxd command."
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
