#!/bin/sh
set -e
set -u

installer_name="wlclipboard"
installer_description="Installs wl-clipboard to allow integration with clipboard in terminal applications."
installer_link="https://archlinux.org/packages/extra/x86_64/wl-clipboard/"

pacman_pkg="extra/wl-clipboard"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "wl-copy [-p | --primary] [-t <mime> | --type <mime>] [text...]"
    htext
    htext "wl-paste [-p | --primary] [-t <mime> | --type <mime>]"
    hexamples
    htext "man wl-clipboard"
    htext
    htext "man wl-copy"
    htext
    htext "man wl-paste"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
