#!/bin/bash

installer_name="pacmancontrib"
installer_description="Installs pacman-contrib to use paccache for cleaning up pacman cache."
installer_link="https://archlinux.org/packages/extra/x86_64/pacman-contrib/"

pacman_pkg="extra/pacman-contrib"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
    htext
    htext "See installer_docs for paccache usage."
}

inst_is_installed() {
    is_pacman_installed ${pacman_pkg}
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install ${pacman_pkg}
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall ${pacman_pkg}
}
