#!/bin/sh
set -e
set -u

installer_name="ghostty"
installer_description="Installs ghostty and copies config file."
installer_link="https://archlinux.org/packages/extra/x86_64/ghostty/"

pacman_pkg="extra/ghostty"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "List built in ghostty themes"
    htext "ls -l /usr/share/ghostty/themes"
    hseealso
    htext "${installer_link}"
    htext "See install_kdeshortcuts"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"

    file_config="${HOME}/.config/ghostty/config"

    mv_bak "${file_config}"

    cp -v config/ghostty.config "${file_config}"

    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
