#!/bin/sh

installer_name="kdesettings"
installer_description="Configures kde settings such as natural scrolling."
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "systemsettings"
    hexamples
    htext "View modules in systemsetting"
    htext "systemsettings --list"
    htext
    htext "Open a specific module like kcm_touchpad"
    htext "systemsettings kcm_touchpad"
    htext
    htext "View input device properties"
    htext "busctl --user introspect org.kde.KWin /org/kde/KWin/InputDevice/event11 org.kde.KWin.InputDevice"
    hseealso
    htext "${installer_link}"
    htext "kciminputrc file"
    htext "Created in .config/kcminputrc after a setting is modified."
    htext
    htext "https://discuss.kde.org/t/ambidextrous-how-to-write-a-script-to-switch-mouse-buttons/38494"
    htext "https://discuss.kde.org/t/changing-mouse-buttonrebinds-for-extrabuttons-programmatically-kcminputrc/42174"
    htext "https://www.reddit.com/r/kde/comments/1odxxhg/any_documentation_for_editing_kcminputrc/"
    htext "https://discuss.kde.org/t/how-to-change-settings-through-command-line/41361"
}

inst_is_installed() {
  return 1
}

inst_can_install() {
  if ! is_command libinput; then
    echo "missing libinput"
    return 1
  fi
  
  if ! is_command udevadm; then
    echo "missing udevadm"
    return 1
  fi
   
  return 0
}


set_inputdevice_prop() {
  arg_dev_path="${1}"
  arg_prop="${2}"
  arg_type="${3}"
  arg_val="${4}"

  dev_name=$(udevadm info "${arg_dev_path}" | grep "M:" | tr -d "M: ")
  if [ "/dev/input/${dev_name}" != "${arg_dev_path}" ]; then
    echo "failed to find device name from ${arg_dev_path} got: ${dev_name}"
    return 1
  fi


  val_before=$(busctl --user get-property org.kde.KWin "/org/kde/KWin/InputDevice/${dev_name}" org.kde.KWin.InputDevice "${arg_prop}")
  busctl --user set-property org.kde.KWin "/org/kde/KWin/InputDevice/${dev_name}" org.kde.KWin.InputDevice "${arg_prop}" "${arg_type}" "${arg_val}"
  val_after=$(busctl --user get-property org.kde.KWin "/org/kde/KWin/InputDevice/${dev_name}" org.kde.KWin.InputDevice "${arg_prop}")
  
  echo "set input device property"
  echo "dev path:    ${arg_dev_path}"
  echo "dev name:    ${dev_name}"
  echo "property:    ${arg_prop}"
  echo "before:      ${val_before}"
  echo "after:       ${val_after}"
}

config_touchpad() {
  echo "configuring touchpad: libinput list-devices will be called with sudo"

  dev_substring="Touchpad"
  num_substring_lines=$(sudo libinput list-devices | grep -c "${dev_substring}")
  if [ "${num_substring_lines}" -ne "1" ]; then
    echo "too many ${dev_substring} results expected 1 got ${num_substring_lines}"
    return 0
  fi
  
  dev_path=$(sudo libinput list-devices | grep "${dev_substring}" -A 1 | tail -n 1 | tr -s " " "\n" | tail -n 1)

  set_inputdevice_prop "${dev_path}" naturalScroll b true
}

inst_install() {
  config_touchpad

  # systemsettings kcm_smserver
  kwriteconfig6 --file ksmserverrc --group General --key loginMode emptySession

  return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    return 0
}
