#!/bin/sh

installer_name="md4c"
installer_description="Installs md4c."
installer_link="https://archlinux.org/packages/extra/x86_64/md4c/"

pacman_pkg="extra/md4c"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Convert md to html"
    htext "md2html -f -o file.html file.md"
    hseealso
    htext "${installer_link}"
    htext "https://github.com/mity/md4c"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
