#!/bin/sh

installer_name="docker"
installer_description="Installs docker."
installer_link="https://archlinux.org/packages/extra/x86_64/docker/"

pacman_pkg="extra/docker"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"

    enable_start_service docker.service
}

inst_can_install_manual() {
    return 0
}

inst_install_manual() {
    echo "Add yourself to the docker group"
    echo "1) Check which groups you belong to"
    echo "groups"
    echo "2) Add to docker group"
    echo "sudo groupadd docker"
    echo "sudo usermod -aG docker ${USER}"
    echo "3) Reboot"
    echo "reboot"

    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
