#!/bin/sh

installer_name="unzip"
installer_description="Installs unzip."
installer_link="https://archlinux.org/packages/extra/x86_64/unzip/"

pacman_pkg="extra/unzip"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Uncompress a file"
    htext "unzip file.tar.zip file.tar"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
