#!/bin/sh

installer_name="entr"
installer_description="Installs entr."
installer_link="https://archlinux.org/packages/extra/x86_64/entr/"

pacman_pkg="extra/entr"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Listen for file changes (and skip first call) and send a notification in the background"
    htext "echo file | entr -n -p -s 'notify-send \"MODIFIED\" \"file was modified\"' &"
    htext
    htext "Automatically update html file on md file changes"
    htext "echo 2026-05-the-linux-command-line.md | entr -s 'md2html -f -o \"\${0%.md}.html\" \"\${0}\"'"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
