#!/bin/sh

installer_name="ollama"
installer_description="Installs ollama."
installer_link="https://archlinux.org/packages/extra/x86_64/ollama-vulkan/"

pacman_pkg="extra/ollama-vulkan"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "Start the server"
    htext "OLLAMA_VULKAN=1 OLLAMA_IGPU_ENABLE=1 OLLAMA_FLASH_ATTENTION=1 OLLAMA_CONTEXT_LENGTH=32768 ollama serve"
    htext
    htext "Pull a model"
    htext "ollama pull gemma4:e4b"
    htext
    htext "Run a model"
    htext "ollama run qwen3.5:9b"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 0
}

inst_install_manual() {
    echo "1. Start the server"
    echo "ollama server"
    echo "2. Run the model"
    echo "ollama run qwen3.5:9b"

    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
