#!/bin/bash

# Docs
# usage:
#   1. create a tar archive
#   tar -c -v -f filedir.tar filedir
#
#   2. extract a tar archive
#   tar -x -v -f filedir.tar filedir 

installer_name="tar"
installer_description="installs tar"
installer_link="https://archlinux.org/packages/core/x86_64/tar/"

SHORT_PKG="tar"
LONG_PKG="core/${SHORT_PKG}"

inst_is_installed() {
    is_pacman_installed ${SHORT_PKG}
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install ${LONG_PKG}
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_can_upgrade() {
    return 1
}

inst_upgrade() {
    return 1
}

inst_uninstall() {
    pacman_uninstall ${SHORT_PKG}
}

