#!/bin/sh

installer_name="calibre"
installer_description="Installs calibre."
installer_link="https://archlinux.org/packages/extra/x86_64/calibre/"

pacman_pkg="extra/calibre"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "calibre -h"
    hexamples
    htext "Convert an epub to azw3"
    htext "ebook-convert file.epub file.azw3"
    htext
    htext "Get help for a given conversion"
    htext "ebook-convert FILE_FROM FILE_TO -h"
    htext
    htext "Complete guide to upload an epub to the kindle"
    htext
    htext "1) convert to azw3 format"
    htext "ebook-convert file.epub file.azw3"
    htext
    htext "2) Connect the usb and find the device"
    htext
    htext "2.1) Check dmesg for something containing kindle"
    htext "sudo dmesg"
    htext
    htext "2.2) Check block devices"
    htext "lsblk"
    htext
    htext "2.3) Verify correct device"
    htext "udevadm info /dev/sda"
    htext
    htext "3) Mount the filesystem"
    htext "sudo mkdir -p /mnt/kindle"
    htext "sudo mount /dev/sda /mnt/kindle"
    htext
    htext "4) Create folder in documents"
    htext "sudo mkdir -p /mnt/kindle/documents/arch-uploads"
    htext
    htext "5) Copy file"
    htext "sudo cp file.azw3 /mnt/kindle/documents/arch-uploads"
    htext
    htext "6) Unmount the filesystem"
    htext "sudo umount /dev/sda"
    hseealso
    htext "${installer_link}"
    htext
    htext "Command Line Interface"
    htext "https://manual.calibre-ebook.com/generated/en/cli-index.html"
    htext
    htext "Calibre GitHub repository"
    htext "https://github.com/kovidgoyal/calibre"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

install_calibre_config_db() {
    file_calibre_config="${HOME}/.config/calibre/global.py.json"

    if [ ! -f "${file_calibre_config}" ]; then
        bold_red "file ${file_calibre_config} does not exist"
        return 1
    fi

    database_path="${HOME}/.local/share/calibre/library1.db"
    library_path="${HOME}/.local/.share/calibre/lib"

    mkdir -p "${library_path}"

    cp_bak "${file_calibre_config}"
    sed -i "s|\"database_path\".*|\"database_path\": \"${database_path}\",|" "${file_calibre_config}"
    sed -i "s|\"library_path\".*|\"library_path\": \"${library_path}\",|" "${file_calibre_config}"

    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"

    install_calibre_config_db
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
