#!/bin/bash

installer_name="docs"
installer_description="Just documentation."
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Delete # characters"
    htext 'echo "H#e##ll#o W###orld#" | tr -d "#"'
    htext
    htext "Create two columns using colon as separtor"
    htext 'echo "v1:v2" | column --table -s ":" -C "name=INSTALL FILE,width=25,strictwidth" -C "name=DOCUMENTATION" -l 2'
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    return 0
}
