#!/bin/bash

# Docs
# N/A

installer_name="nvim"
installer_description="installs neovim"
installer_link="https://archlinux.org/packages/extra/x86_64/neovim/"

SHORT_PKG="neovim"
LONG_PKG="extra/${SHORT_PKG}"

inst_is_installed() {
    return 1
}

inst_can_install() {
    if ! is_command "unzip"; then
        return 1
    fi
    
    return 0
}

inst_install() {
    if ! is_pacman_installed ${SHORT_PKG}; then
        pacman_install ${LONG_PKG}
    fi
    
    mkdir $HOME/.config/nvim 2>/dev/null
    
    cp config/nvim/init.lua $HOME/.config/nvim/init.lua
    cp config/nvim/stylua.toml $HOME/.config/nvim/.stylua.toml
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_can_upgrade() {
    return 1
}

inst_upgrade() {
    return 0
}

inst_uninstall() {
    pacman_uninstall ${SHORT_PKG}
}

