#!/bin/sh

installer_name="d2"
installer_description="Installs d2 to generate diagrams."
installer_link="https://archlinux.org/packages/extra/x86_64/d2/"

pacman_pkg="extra/d2"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "d2 file.d2 out"
    hexamples
    htext "Using docs/d2/simple-example.d2 producing svg"
    htext "d2 --ascii-mode standard docs/d2/simple-example.d2 out.svg"
    htext
    htext "Using docs/d2/simple-example.d2 producing ascii unicode"
    htext "d2 --ascii-mode extended docs/d2/simple-example.d2 out.txt"
    htext
    htext "Using docs/d2/simple-example.d2 producing ascii standard"
    htext "d2 --ascii-mode standard docs/d2/simple-example.d2 out.txt"
    htext
    htext "Opening preview pane for d2 in nvim"
    htext "<Leader>d2"
    hseealso
    htext "${installer_link}"
    htext "https://d2lang.com/blog/ascii/"
    htext "https://d2lang.com/blog/tala-is-open-source/"
    htext
    htext "D2 Vim/Nvim plugin"
    htext "https://github.com/d2lang/d2-vim"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
