#!/bin/bash

# usage:
#   1. compress a file
#   gzip --keep file.tar
#
#   2. uncompress a file
#   gzip --keep -d file.tar.gz

installer_name="gzip"
installer_description="installs gzip"
installer_link="https://archlinux.org/packages/core/x86_64/gzip/"

SHORT_PKG="gzip"
LONG_PKG="core/${SHORT_PKG}"

inst_is_installed() {
    is_pacman_installed ${SHORT_PKG}
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install ${LONG_PKG}
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_can_upgrade() {
    return 1
}

inst_upgrade() {
    return 1
}

inst_uninstall() {
    pacman_uninstall ${SHORT_PKG}
}

