#!/bin/bash

installer_name="nvim"
installer_description="Installs neovim."
installer_link="https://archlinux.org/packages/extra/x86_64/neovim/"

pacman_pkg="extra/neovim"

nvim_src=config/nvim
nvim_dst=$HOME/.config/nvim

cp_parser() {
    arg_so_file="${1}"
    arg_lang="${2}"

    parser_file="${nvim_dst}/parser/${arg_lang}.so"
    bak_dir="${nvim_dst}/parser/bak"
    mkdir -p ${bak_dir}

    mv_bak ${parser_file} ${bak_dir}
    cp -v ${arg_so_file} ${parser_file}
}

handle_tree_sitter_java() {
    repo="https://github.com/tree-sitter/tree-sitter-java"
    dest_dir="$HOME/Documents/tree-sitter-java"

    if [ ! -d $dest_dir ]; then
        echo "git clone ${repo}"
        if ! git clone ${repo} ${dest_dir} 1>/dev/null 2>&1; then
            echo "git clone failed!"
            return 0
        fi
    fi
   
    echo "git pull ${dest_dir}"
    if ! git -C ${dest_dir} pull 1>/dev/null 2>&1; then
        echo "git pull failed"
        return 0
    fi
    
    make -C ${dest_dir} 1>/dev/null

    so_file="${dest_dir}/libtree-sitter-java.so"

    if [ ! -f ${so_file} ]; then
        echo "make failed missing ${so_file}"
        return 0
    fi

    cp_parser ${so_file} "java"
    
    return 0
}

cp_query() {
    arg_lang="${1}"
    lang_dir_dst=${nvim_dst}/queries/${arg_lang}

    mkdir -p ${lang_dir_dst}
    cp -v ${nvim_src}/queries/${arg_lang}/highlights.scm ${lang_dir_dst}/highlights.scm
}


inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    if ! is_command "unzip"; then
        echo "missing unzip"
        return 1
    fi
    
    return 0
}

inst_install() {
    if ! is_pacman_installed ${pacman_pkg}; then
        pacman_install ${pacman_pkg}
    fi
    
    mkdir $HOME/.config/nvim 2>/dev/null
    mkdir $HOME/.config/nvim/colors 2>/dev/null
    mkdir $HOME/.config/nvim/lua 2>/dev/null
    
    cp -v config/nvim/init.lua $HOME/.config/nvim/init.lua
    cp -v config/nvim/stylua.toml $HOME/.config/nvim/.stylua.toml

    cp_query "java"
    cp_query "c"

    handle_tree_sitter_java
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall ${pacman_pkg}
}
