#!/bin/bash

installer_name="gzip"
installer_description="installs gzip"
installer_link="https://archlinux.org/packages/core/x86_64/gzip/"

pacman_pkg="core/gzip"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Compress a file"
    htext "gzip --keep file.tar"
    htext
    htext "Uncompress a file"
    htext "gzip --keep -d file.tar.gz"
    hseealso
    htext "${installer_link}"
    htext "ANOTHER_LINK_ANOTHER_LINK"
}

inst_is_installed() {
    is_pacman_installed ${pacman_pkg}
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install ${pacman_pkg}
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall ${pacman_pkg}
}
