#!/bin/sh
set -e
set -u

installer_name="calibre"
installer_description="Installs calibre."
installer_link="https://archlinux.org/packages/extra/x86_64/calibre/"

pacman_pkg="extra/calibre"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "TODO"
    hexamples
    htext "TODO"
    hseealso
    htext "${installer_link}"
    htext
    htext "Command Line Interface"
    htext "https://manual.calibre-ebook.com/generated/en/cli-index.html"
    htext
    htext "Calibre GitHub repository"
    htext "https://github.com/kovidgoyal/calibre"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    return 0
    # pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
