#!/bin/sh

installer_name="jq"
installer_description="Installs jq."
installer_link="https://archlinux.org/packages/extra/x86_64/jq/"

pacman_pkg="extra/jq"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Delete id and items.id (two alternatives)"
    htext "jq 'del(.id) | .items |= map(del(.id))' JSON"
    htext "jq 'del(.id) | .items[] |= del(.id)' JSON"
    htext
    htext "Rename items.name to items.year"
    htext "jq '.items |= map(.year = .name | del(.name))' JSON"
    hseealso
    htext "${installer_link}"
    htext "https://jqlang.org/manual/"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
