#!/bin/bash

# Docs
# 1. https://www.youtube.com/watch?v=ttZKwrR6xKQ

installer_name="brave"
installer_description="installs brave and configures kde defaults"
installer_link="https://aur.archlinux.org/packages/brave-bin"

SHORT_PKG="brave-bin"
BRAVE_DESKTOP="brave-browser.desktop"
BRAVE_SYNC_CODE="config/brave-sync-code.txt"

inst_is_installed() {
    is_command brave
}

inst_can_install() {
    if ! is_command git; then
        echo "requires git"
        return 1
    fi

    if [[ -f "${BRAVE_SYNC_CODE}" ]]; then
        echo "missing file ${BRAVE_SYNC_CODE}"
        return 1
    fi

    return 0
}

inst_install() {
    mkdir ~/aur-builds
    cd ~/aur-builds
    git clone https://aur.archlinux.org/brave-bin.git
    cd brave-bin

    makepkg --noconfirm -si

    kwriteconfig6 --file kdeglobals --group General --key BrowserApplication "${BRAVE_DESKTOP}"
    kwriteconfig6 --file kdeglobals --group General --key Http "${BRAVE_DESKTOP}"
    kwriteconfig6 --file kdeglobals --group General --key Https "${BRAVE_DESKTOP}"

    rm -rf ~/aur-builds/brave-bin

    return 0
}

inst_can_install_manual() {
    return 0
}

inst_install_manual() {
    echo "1. sync setup: settings > sync > I have a Sync Code (code printed next)"
    cat "${BRAVE_SYNC_CODE}"

    return 0
}

inst_can_upgrade() {
    return 0
}

inst_upgrade() {
    return 0
}

inst_uninstall() {
    pacman_uninstall ${SHORT_PKG}
}

