#!/bin/bash

installer_name="postman"
installer_description="Installs postman desktop."
installer_link="https://aur.archlinux.org/packages/postman-bin"

pacman_pkg="postman-bin"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "postman"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
}

# TODO: how to re-install AUR packages? Create arg to inst_install OPT_2. Also remove check here then for is_command
inst_is_installed() {
    is_command postman
}

inst_can_install() {
    if ! is_command git; then
        echo "missing git"
        return 1
    fi

    return 0
}

# TODO: create AUR helper
inst_install() {
    aur_build_dir=$HOME/aur-builds/postman-bin
    git clone https://aur.archlinux.org/postman-bin.git ${aur_build_dir}

    makepkg --noconfirm -si --dir ${aur_build_dir}

    rm -rf ${aur_build_dir}

    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall ${pacman_pkg}
}
