#!/bin/sh
set -e
set -u

# TODO:
# Docs
# 1. link to nuphy
# 2. other...
# remove the nuphy keyboard md -> move into here

installer_name="nuphykeyboard"
installer_description="Explains how to configure the nuphy halo v2 keyboard."
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 0
}

inst_can_install() {
    return 1
}

inst_install() {
    return 0
}

inst_can_install_manual() {
    return 0
}

inst_install_manual() {
    echo "1. copy file to somewhere"
    echo "2. then do this"
    return 0
}

inst_uninstall() {
     return 0
}
