#!/bin/sh
set -e
set -u

installer_name="gitleaks"
installer_description="Installs gitleaks."
installer_link="https://archlinux.org/packages/extra/x86_64/gitleaks/"

pacman_pkg="extra/gitleaks"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "gitleaks --help"
    hexamples
    htext "Search for leaks"
    htext "gitleaks detect --source . --log-opts=\"--all\" -v"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
