#!/bin/bash
sudo pacman --noconfirm -S extra/archlinux-wallpaper

echo "install_wallpaper: installed wallpapers list below"
ls -1 /usr/share/backgrounds/archlinux

# Package: https://archlinux.org/packages/extra/any/archlinux-wallpaper/
# Post: https://bbs.archlinux.org/viewtopic.php?id=259604

readonly WP="/usr/share/backgrounds/archlinux/conference.png"
readonly LS="/usr/share/backgrounds/archlinux/simple.png"

# Sets wallpaper
plasma-apply-wallpaperimage "${WP}"

# Sets lock screen
kwriteconfig6 --file kscreenlockerrc --group Greeter --group Wallpaper --group org.kde.image --group General --key Image "file://${LS}"
