#!/bin/bash

installer_name="ghostty"
installer_description="installs ghostty"
installer_link="https://archlinux.org/packages/extra/x86_64/ghostty/"

SHORT_PKG="ghostty"
LONG_PKG="extra/${SHORT_PKG}"

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    if ! is_pacman_installed ${SHORT_PKG}; then
        pacman_install ${LONG_PKG}
    fi
    
    echo "copying ghostty config file" 
    cp config/ghostty.config ${HOME}/.config/ghostty/config

    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_can_upgrade() {
    return 1
}

inst_upgrade() {
    return 1
}

inst_uninstall() {
    pacman_uninstall ${SHORT_PKG}
}
