#!/bin/sh

installer_name="kdeshortcuts"
installer_description="Configures shortcuts for KDE Plasma 6"
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
    htext
    htext "You can figure out the bindings by going to System Settings > Keyboard > Shortcuts > Export."
    htext "The resulting kksrc file can be inspected."
    htext "For example Window Maximize is in file kglobalshortcutsrc and group kwin, see [kwin][Global Shortcuts]."
    htext
    htext "Another way to find the configureations is by inspecting /home/ludvig/.config/kglobalshortcutsrc."
    htext "Issue with this approach is that it's not always in this file. For example the krunner"
    htext "shortcut was like this in the kksrc export file:"
    htext "[org.kde.krunner.desktop][Global Shortcuts]"
    htext "RunClipboard=Alt+Shift+F2"
    htext "_launch=Search; Alt+Space; Alt+F2"
    htext
    htext "This cannot be found in the kglobalshortcutsrc file, it seems like it is not written"
    htext "unless overridden. The desktop file was then found by running the following from /:"
    htext "find . -name org.kde.krunner.desktop 2>/dev/null"
    htext "/usr/share/kglobalaccel/org.kde.krunner.desktop"
    htext
    htext "Then inspecting this file was this line:"
    htext "X-KDE-Shortcuts=Alt+Space,Alt+F2,Search"
    htext "However, that did not really help as it turned out the actual value needed to have tabs in them."
    htext "The way I found that out was by saving it in system settings, then inspecting the config value in the kglobalshortcutsrc file."
    htext "The end result being the printf solution below."
    htext
    htext "Regarding ghostty +new-window is recommended in docs, see https://ghostty.org/docs/linux/systemd"
    htext
    htext "Qdbus service/bus and object path help example"
    htext "qdbus6 org.kde.KWin /VirtualDesktopManager"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

create_desktop_file_shortcut() {
    arg_name="${1}"
    arg_exec="${2}"
    arg_shortcut="${3}"

    file_desktop="net.local.${arg_name}.desktop"
    file_desktop_path="${HOME}/.local/share/applications/${file_desktop}"

    mv_bak "${file_desktop_path}"

    {
        echo "[Desktop Entry]"
        echo "Exec=${arg_exec}"
        echo "Name=${arg_name}"
        echo "NoDisplay=true"
        echo "StartupNotify=false"
        echo "Type=Application"
        echo "X-KDE-GlobalAccel-CommandShortcut=true"
    } >>"${file_desktop_path}"

    kwriteconfig6 --file kglobalshortcutsrc --group services --group "${file_desktop}" --key _launch "${arg_shortcut}"

    return 0
}

inst_install() {
    kwriteconfig6 --file kglobalshortcutsrc --group kwin --key "Window Maximize" "Meta+Shift+Up,Meta+PgUp,Maximize Window"
    kwriteconfig6 --file kglobalshortcutsrc --group kwin --key "Window Close" "Meta+Shift+W,Meta+Shift+W,Close Window"
    kwriteconfig6 --file kglobalshortcutsrc --group services --group org.kde.krunner.desktop --key _launch "$(printf "Alt+F2\tSearch\t")"

    create_desktop_file_shortcut "ghosttynewwindow" "ghostty +new-window" "Alt+Space"

    echo "log out and back in for changes to take effect (run slogout)!"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    return 0
}
