#!/bin/sh

installer_name="brave"
installer_description="Installs brave and configures kde defaults."
installer_link="https://aur.archlinux.org/packages/brave-bin/"

pacman_pkg="brave-bin"

brave_desktop="brave-browser.desktop"
brave_sync_code="config/brave-sync-code.txt"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "brave [options] [PATH]"
    hexamples
    htext "brave PATH"
    htext
    htext "brave --incognito PATH"
    htext
    htext "brave --new-window PATH"
    htext
    htext "brave --app=PATH"
    hseealso
    htext "${installer_link}"
    htext "https://www.youtube.com/watch?v=ttZKwrR6xKQ"
    htext "https://linuxcommandlibrary.com/man/brave"
    htext "https://man.linuxreviews.org/man1/brave-browser-stable.1.html"
}

inst_is_installed() {
    is_command brave
}

inst_can_install() {
    if ! is_command git; then
        echo "requires git"
        return 1
    fi

    if [ ! -f "${brave_sync_code}" ]; then
        echo "missing file ${brave_sync_code}"
        return 1
    fi

    return 0
}

inst_install() {
    aur_build_dir="${HOME}/aur-builds/brave-bin"
    git clone https://aur.archlinux.org/brave-bin.git "${aur_build_dir}"

    makepkg --noconfirm -si --dir "${aur_build_dir}"

    # TODO: replace 4 spaces with 2 across all files
    # TODO: create helper for kwriteconfig, searrch across
    # TODO: create helper to clone and build AUR PACKAGE
    # TODO: make all variables lowercase
    kwriteconfig6 --file kdeglobals --group General --key BrowserApplication "${brave_desktop}"
    kwriteconfig6 --file kdeglobals --group General --key Http "${brave_desktop}"
    kwriteconfig6 --file kdeglobals --group General --key Https "${brave_desktop}"

    rm -rf "${aur_build_dir}"

    return 0
}

inst_can_install_manual() {
    return 0
}

inst_install_manual() {
    echo "1. sync setup: settings > sync > I have a Sync Code (code printed next)"

    if [ ! -f "${brave_sync_code}" ]; then
        echo "missing ${brave_sync_code}"
    else
        cat "${brave_sync_code}"
    fi

    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
