#!/bin/sh

installer_name="nvim"
installer_description="Installs neovim."
installer_link="https://archlinux.org/packages/extra/x86_64/neovim/"

pacman_pkg="extra/neovim"

nvim_src=config/nvim
nvim_dst="${HOME}/.config/nvim"

git_clone_pull() {
    arg_repo="${1}"
    arg_dest_dir="${2}"

    if [ ! -d "${arg_dest_dir}" ]; then
        echo "git clone ${arg_repo}"
        if ! git clone "${arg_repo}" "${arg_dest_dir}" 1>/dev/null 2>&1; then
            echo "git clone failed!"
            return 0
        fi
    fi

    echo "git pull ${arg_dest_dir}"
    if ! git -C "${arg_dest_dir}" pull 1>/dev/null 2>&1; then
        echo "git pull failed"
        return 0
    fi

    return 0
}

handle_vscode_test() {
    version="0.45.0"
    vsix_url="https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vscjava/vsextensions/vscode-java-test/${version}/vspackage"
    dest_dir="${HOME}/Documents/vscode-java-test"
    dest_file_gz="${dest_dir}/vscodetest.vsix.gz"
    dest_file_zip="${dest_dir}/vscodetest.vsix"

    jar_file="$(ls "${dest_dir}"/extension/server/*.jar 2>/dev/null)"
    if [ "${jar_file}" != "" ]; then
        echo "handle_vscode_test: skipping found vscode test ${version} jar files"
        return 0
    fi

    mkdir -p "${dest_dir}"

    echo "downloading ${vsix_url}"
    curl -L -o "${dest_file_gz}" "${vsix_url}"

    echo "decompressing ${dest_file_gz}"
    gzip --force -d "${dest_file_gz}"

    echo "unzipping ${dest_file_zip}"
    unzip -o "${dest_file_zip}" -d "${dest_dir}"
}

handle_java_debug() {
    repo="https://github.com/microsoft/java-debug"
    dest_dir="${HOME}/Documents/java-debug"

    c1="com.microsoft.java.debug.plugin"
    jar_file="$(ls "${dest_dir}/${c1}/target/${c1}"-*.jar 2>/dev/null)"

    if [ "${jar_file}" = "" ]; then
        git_clone_pull "${repo}" "${dest_dir}"
        mvn -f "${dest_dir}/pom.xml" clean install
    else
        echo "handle_java_debug: skipping found java debug jar files"
    fi
}

cp_parser() {
    arg_so_file="${1}"
    arg_lang="${2}"

    parser_file="${nvim_dst}/parser/${arg_lang}.so"

    mv_bak "${parser_file}"
    cp -v "${arg_so_file}" "${parser_file}"
}

handle_tree_sitter_bash() {
    repo="https://github.com/tree-sitter/tree-sitter-bash"
    dest_dir="${HOME}/Documents/tree-sitter-bash"
    so_file="${dest_dir}/libtree-sitter-bash.so"

    if [ -f "${so_file}" ]; then
        echo "handle_tree_sitter_bash: skipping file ${so_file} exists"
        return 0
    fi

    git_clone_pull "${repo}" "${dest_dir}"

    make -C "${dest_dir}" 1>/dev/null

    if [ ! -f "${so_file}" ]; then
        echo "make failed missing ${so_file}"
        return 0
    fi

    cp_parser "${so_file}" bash

    return 0
}

handle_tree_sitter_java() {
    repo="https://github.com/tree-sitter/tree-sitter-java"
    dest_dir="${HOME}/Documents/tree-sitter-java"
    so_file="${dest_dir}/libtree-sitter-java.so"

    if [ -f "${so_file}" ]; then
        echo "handle_tree_sitter_java: skipping file ${so_file} exists"
        return 0
    fi

    git_clone_pull "${repo}" "${dest_dir}"

    make -C "${dest_dir}" 1>/dev/null

    if [ ! -f "${so_file}" ]; then
        echo "make failed missing ${so_file}"
        return 0
    fi

    cp_parser "${so_file}" java

    return 0
}

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    htext
    htext "Also builds java parsers, debug and test jars"
    husage
    htext "-"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
    htext
    htext "Delete all temporary nvim related files to start fresh"
    htext "rm -rf ~/.config/nvim"
    htext "rm -rf ~/.local/share/nvim"
    htext "rm -rf ~/.local/state/nvim"
    htext "rm -rf ~/.cache/nvim"
    htext
    htext "Java Debug Server repository"
    htext "https://github.com/microsoft/java-debug"
    htext
    htext "Test runner for java repository"
    htext "https://github.com/microsoft/vscode-java-test"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    if ! is_command unzip; then
        echo "missing unzip"
        return 1
    fi

    if ! is_command mvn; then
        echo "missing mvn"
        return 1
    fi

    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"

    mkdir "${nvim_dst}" 2>/dev/null
    mkdir "${nvim_dst}/colors" 2>/dev/null
    mkdir "${nvim_dst}/lua" 2>/dev/null
    mkdir "${nvim_dst}/parser" 2>/dev/null
    mkdir "${nvim_dst}/queries" 2>/dev/null
    mkdir "${nvim_dst}/ftplugin" 2>/dev/null
    mkdir "${nvim_dst}/formatters" 2>/dev/null
    mkdir "${nvim_dst}/snippets" 2>/dev/null

    cp -v "${nvim_src}/init.lua" "${nvim_dst}/init.lua"

    # lwcs
    mkdir "${nvim_dst}/lua/lwcs" 2>/dev/null
    cp -v "${nvim_src}/colors/lwcs.lua" "${nvim_dst}/colors/lwcs.lua"
    cp -v "${nvim_src}/lua/lwcs/groups.lua" "${nvim_dst}/lua/lwcs/groups.lua"
    cp -v "${nvim_src}/lua/lwcs/init.lua" "${nvim_dst}/lua/lwcs/init.lua"

    # lwcsmac
    mkdir "${nvim_dst}/lua/lwcsmac" 2>/dev/null
    cp -v "${nvim_src}/colors/lwcsmac.lua" "${nvim_dst}/colors/lwcsmac.lua"
    cp -v "${nvim_src}/lua/lwcsmac/groups.lua" "${nvim_dst}/lua/lwcsmac/groups.lua"
    cp -v "${nvim_src}/lua/lwcsmac/init.lua" "${nvim_dst}/lua/lwcsmac/init.lua"

    # abbreviations
    cp -v "${nvim_src}/lua/abbreviations.lua" "${nvim_dst}/lua/abbreviations.lua"

    # queries c
    mkdir "${nvim_dst}/queries/c" 2>/dev/null
    cp -v "${nvim_src}/queries/c/highlights.scm" "${nvim_dst}/queries/c/highlights.scm"

    # queries java
    mkdir "${nvim_dst}/queries/java" 2>/dev/null
    cp -v "${nvim_src}/queries/java/highlights.scm" "${nvim_dst}/queries/java/highlights.scm"

    # queries bash
    mkdir "${nvim_dst}/queries/bash" 2>/dev/null
    cp -v "${nvim_src}/queries/bash/highlights.scm" "${nvim_dst}/queries/bash/highlights.scm"

    # ftplugin
    cp -v "${nvim_src}/ftplugin/java.lua" "${nvim_dst}/ftplugin/java.lua"

    # formatters
    cp -v "${nvim_src}/formatters/intellij-codestyle.xml" "${nvim_dst}/formatters/intellij-codestyle.xml"
    cp -v "${nvim_src}/formatters/.clang-format" "${nvim_dst}/formatters/.clang-format"
    cp -v "${nvim_src}/formatters/.stylua.toml" "${nvim_dst}/formatters/.stylua.toml"
    cp -v "${nvim_src}/formatters/jdtls.prefs" "${nvim_dst}/formatters/jdtls.prefs"

    # snippets
    cp -v "${nvim_src}/snippets/java.lua" "${nvim_dst}/snippets/java.lua"

    handle_tree_sitter_java
    handle_tree_sitter_bash

    handle_java_debug

    handle_vscode_test
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
