#!/bin/sh

installer_name="groff"
installer_description="Installs groff."
installer_link="https://archlinux.org/packages/core/x86_64/groff/"

pacman_pkg="core/groff"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "man groff"
    hexamples
    htext "Compile using ms macro to pdf"
    htext "groff docs/groff/simple-example.ms -ms -T pdf > out.pdf"
    htext
    htext "Compile using mom macro to pdf"
    htext "groff docs/groff/tutorial.mom -mom -T pdf > out.pdf"
    htext
    htext "Compile using mom macro to pdf with entr"
    htext "echo docs/groff/tutorial.mom | entr -s 'groff \"\${0}\" -mom -T pdf > \"\${0%.mom}.pdf\"'"
    hseealso
    htext "${installer_link}"
    htext "https://wiki.archlinux.org/title/Groff"
    htext
    htext "Macro mom documentation"
    htext "https://www.schaffter.ca/mom/momdoc/intro.html#intro-intro"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
