#!/bin/sh

installer_name="icu"
installer_description="Installs icu."
installer_link="https://archlinux.org/packages/core/x86_64/icu/"

pacman_pkg="core/icu"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Show unicode character number"
    htext "echo -n 'ö' | uconv -x 'any-hex'"
    htext
    htext "Convert from UTF-8 to ISO-8859-1"
    htext "uconv -f UTF-8 -t ISO-8859-1 FILE > OUT"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
