#!/bin/sh

installer_name="mariadbclients"
installer_description="Installs mariadbclients."
installer_link="https://archlinux.org/packages/extra/x86_64/mariadb-clients/"

pacman_pkg="extra/mariadb-clients"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "mariadb --help"
    hexamples
    htext "Connect to db on localhost"
    htext "mariadb -h localhost -P 30010 -u root -phere --ssl=false sakra"
    htext
    htext "Show default settings from my.cnf"
    htext "mariadb --print-defaults"
    htext
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"

    file_config="${HOME}/.my.cnf"

    mv_bak "${file_config}"

    cp -v config/my.cnf "${file_config}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
