#!/bin/sh

installer_name="slack"
installer_description="Installs slack desktop."
installer_link="https://aur.archlinux.org/packages/slack-desktop"

pacman_pkg="slack-desktop"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "slack"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    if is_aur_reinstall; then
        return 1
    fi

    is_command slack
}

inst_can_install() {
    if ! is_command git; then
        echo "missing git"
        return 1
    fi

    return 0
}

inst_install() {
    aur_install slack-desktop

    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
