#!/bin/sh

installer_name="docs_keybinds_arch"
installer_description="Arch keybindings documentation."
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Toggle fullscreen windowed"
    htext "<M-S-Up>"
    htext
    htext "Resize to tile"
    htext "<M-Up>"
    htext "<M-Down>"
    htext "<M-Left>"
    htext "<M-Right>"
    htext
    htext "Toggle language"
    htext "<A-S>"
    htext
    htext "Open ghostty"
    htext "<A-Space>"
    htext
    htext "Move to the left/right desktop"
    htext "<M-C-Left>"
    htext "<M-C-Right>"
    htext
    htext "Move window to left/right desktop"
    htext "<M-C-S-Left>"
    htext "<M-C-S-Right>"
    htext
    htext "Close window"
    htext "<M-S-w>"
    htext
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    return 0
}
