#!/bin/sh

installer_name="docs_sed"
installer_description="sed documentation"
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Delete a line that starts and ends with string"
    htext "sed -i '/^string$/d' FILE"
    htext
    htext "Create backup file for -i"
    htext "sed -i.bak OPTIONS"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    return 0
}
