#!/bin/sh

installer_name="archwallpaper"
installer_description="Installs archlinux-wallpaper and configures it."
installer_link="https://archlinux.org/packages/extra/any/archlinux-wallpaper/"

pacman_pkg="extra/archlinux-wallpaper"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "List installed and available wallpapers from ${pacman_pkg}"
    htext "ls -1 /usr/share/backgrounds/archlinux"
    hseealso
    htext "${installer_link}"
    htext "https://bbs.archlinux.org/viewtopic.php?id=259604"
    htext
    htext "Arch Linux minimal wallpapers"
    htext "https://github.com/LagrangianLad/arch-minimal-wallpapers"
    htext
    htext "4K Wallpapers"
    htext "https://4kwallpapers.com/"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"

    wallpaper_dir="${HOME}/.local/share/lwboot/wallpapers"

    if [ ! -d "${wallpaper_dir}" ]; then
        bold_yellow "missing ${wallpaper_dir}"
        return 0
    fi

    wallpaper_files="$(find "${wallpaper_dir}" -regextype posix-basic -type f -regex '\(.*\.jpeg\|.*\.png\)')"

    if [ "${wallpaper_files}" = "" ]; then
        bold_yellow "add some jpeg or png files to ${wallpaper_dir}"
        return 0
    fi

    if ! is_command systemctl; then
        bold_red "missing systemctl"
        return 0
    fi

    service_name="setwallpaper.service"
    service_dir="${HOME}/.config/systemd/user"
    service_file="${service_dir}/${service_name}"

    mkdir -p "${service_dir}"

    setwallpaper_file="${PROG_DIR}/config/install_archwallpaper/setwallpaper"

    {
        echo "[Unit]"
        echo "Description=lwboot set random wallpaper at login"
        echo "PartOf=graphical-session.target"
        echo "After=plasma-workspace.target"
        echo ""
        echo "[Service]"
        echo "Type=oneshot"
        echo "ExecStart=${setwallpaper_file}"
        echo ""
        echo "[Install]"
        echo "WantedBy=plasma-workspace.target"
    } >"${service_file}" || return 1

    chmod 755 "${setwallpaper_file}"

    reload_user_services
    enable_start_user_service "${service_name}"

    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
