#!/bin/bash

installer_name="clang"
installer_description="Installs clang, mainly to get access to clang-format."
installer_link="https://archlinux.org/packages/extra/x86_64/clang/"

pacman_pkg="extra/clang"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
    htext
    htext "ClangFormat"
    htext "https://clang.llvm.org/docs/ClangFormat.html"
    htext
    htext "ClangFormatStyleOptions 22.1.0"
    htext "https://releases.llvm.org/22.1.0/tools/clang/docs/ClangFormatStyleOptions.html"
    htext
    htext "Creating the .clang-format file"
    htext "1) Run the command for foo.java, foo.c, foo.json"
    htext "clang-format -style=Google -assume-filename=foo.java -dump-config > .clang-format.java"
    htext "2) Note the defaults and override as needed"
}

inst_is_installed() {
    is_pacman_installed ${pacman_pkg}
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install ${pacman_pkg}
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall ${pacman_pkg}
}
