#!/bin/sh

installer_name="tar"
installer_description="Installs tar."
installer_link="https://archlinux.org/packages/core/x86_64/tar/"

pacman_pkg="core/tar"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Create a tar archive"
    htext "tar -c -v -f filedir.tar filedir"
    htext
    htext "Extract a tar archive"
    htext "tar -x -v -f filedir.tar filedir"
    htext
    htext "Create a tar but use numbers for user/group names (anonymous mode)"
    htext "tar --numeric-owner -cvf filedir.tar filedir"
    htext
    htext "Set specific owner and group when creating archive (can be combined with --numeric-owner)"
    htext "tar --owner=0 --group=0 -cvf file.tar file"
    htext
    htext "List contents inside tar file"
    htext "tar -tvf file.tar"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
