#!/bin/sh

installer_name="shfmt"
installer_description="Installs shfmt."
installer_link="https://archlinux.org/packages/extra/x86_64/shfmt/"

pacman_pkg="extra/shfmt"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "shfmt --help"
    hexamples
    htext "Formats a sh file and writes to stdout"
    htext "shfmt -i 4 -ci -ln posix FILE"
    htext
    htext "Formats a bash file and writes to stdout (long variant)"
    htext "shfmt --indent 4 --case-indent --language-dialect bash FILE"
    hseealso
    htext "${installer_link}"
    htext
    htext "https://github.com/mvdan/sh"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
