#!/bin/bash

installer_name="git"
installer_description="installs and configures git (contains personal info) - needs less and vim to work properly"
installer_link="https://archlinux.org/packages/extra/x86_64/git/"

SHORT_PKG="git"
LONG_PKG="extra/${SHORT_PKG}"

GIT_MAIL="ludvig.westerdahl.tech.v1@protonmail.com"
GIT_NAME="ludvig"
GIT_EDITOR="vim"

REPOSITORIES=(
    "lwdoc"
    "Scripts"
)
REPOSITORY_PATHS=(
    "${HOME}/Documents/lwdoc"
    "${HOME}/bin/scripts"
)


handle_repository() {
    repo="${1}"
    repo_path="${2}"
    echo "handling ${repo_path}"
    if [[ ! -d "${repo_path}" ]]; then
        echo "cloning ${repo}..."
	      git clone "git@github.com:LudvigWesterdahl/${repo}.git" "${repo_path}"
    fi

    if [[ $(git -C "${repo_path}" branch --show-current) == "master" ]]; then
        echo "pulling ${repo}..."
        git -C "${repo_path}" pull
    else
        echo "skipping pull ${repo} not on master branch!"
    fi
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    if ! is_command "vim"; then
        return 1
    fi

    if ! is_command "less"; then
        return 1
    fi

    return 0
}

inst_install() {
    if ! is_command "git"; then
        pacman_install ${LONG_PKG}
    fi

    git config --global user.email "${GIT_MAIL}"
    git config --global user.name "${GIT_NAME}"
    git config --global core.editor "${GIT_EDITOR}"

    for i in "${!REPOSITORIES[@]}"; do
        handle_repository "${REPOSITORIES[$i]}" "${REPOSITORY_PATHS[$i]}"
    done
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_can_upgrade() {
    return 1
}

inst_upgrade() {
    return 1
}

inst_uninstall() {
    pacman_uninstall ${SHORT_PKG}
}
