#!/bin/sh
set -e
set -u

installer_name="evtest"
installer_description="Installs evtest. Purpose to replace usage of xev which didn't give the MSC_SCAN values."
installer_link="https://archlinux.org/packages/extra/x86_64/evtest/"

pacman_pkg="extra/evtest"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "sudo evtest"
    hexamples
    htext "List all input devices"
    htext "sudo evtest"
    htext
    htext "To monitor a given device X"
    htext "sudo evtest /dev/input/eventX"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    is_pacman_installed "${pacman_pkg}"
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
