#!/bin/sh
set -e
set -u

installer_name="git"
installer_description="Installs and configures git. Also clones repositories."
installer_link="https://archlinux.org/packages/extra/x86_64/git/"

pacman_pkg="extra/git"

git_mail="ludvig.westerdahl.tech.v1@protonmail.com"
git_name="ludvig"
git_editor="vim"

handle_repository() {
    arg_repo="${1}"
    arg_repo_path="${2}"

    echo "handling ${arg_repo_path}"

    if [ ! -d "${arg_repo_path}" ]; then
        echo "cloning ${arg_repo}..."
        if ! git clone "git@github.com:LudvigWesterdahl/${arg_repo}.git" "${arg_repo_path}" 1>/dev/null 2>&1; then
            echo "clone failed"
        fi
    fi

    current_branch=$(git -C "${arg_repo_path}" branch --show-current) || {
        echo "failed to get current branch in ${arg_repo_path}"
        return 1
    }
}

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    if ! is_command vim; then
        echo "missing vim"
        return 1
    fi

    if ! is_command less; then
        echo "missing less"
        return 1
    fi

    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"

    git config --global user.email "${git_mail}"
    git config --global user.name "${git_name}"
    git config --global core.editor "${git_editor}"
    git config --global init.defaultBranch "master"

    handle_repository "lwdoc" "${HOME}/Documents/lwdoc"
    handle_repository "Scripts" "${HOME}/bin/scripts"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
