#!/bin/bash

# Docs
# 1. You can figure out the bindings by going to "System Settings > Keyboard > Shortcuts > Export".
# The resulting kksrc file can be inspected.
# For example "Window Maximize" is in file kglobalshortcutsrc and group kwin, see [kwin][Global Shortcuts].
#
# 2. Another way to find the configureations is by inspecting /home/ludvig/.config/kglobalshortcutsrc.
# Issue with this approach is that it's not always in this file. For example the krunner
# shortcut was like this in the kksrc export file:
# [org.kde.krunner.desktop][Global Shortcuts]
# RunClipboard=Alt+Shift+F2
# _launch=Search; Alt+Space; Alt+F2
#
# This cannot be found in the kglobalshortcutsrc file, it seems like it is not written
# unless overridden. The desktop file was then found by running the following from /:
# find . -name org.kde.krunner.desktop 2>/dev/null
# /usr/share/kglobalaccel/org.kde.krunner.desktop
#
# Then inspecting this file was this line:
# X-KDE-Shortcuts=Alt+Space,Alt+F2,Search
# However, that did not really help as it turned out the actual value needed to have tabs in them.
# The way I found that out was by saving it in system settings, then inspecting the config value in the kglobalshortcutsrc file.
# The end result being the printf solution below.
#
# 3. Regarding ghostty +new-window is recommended in docs, see https://ghostty.org/docs/linux/systemd

installer_name="kdeshortcuts"
installer_description="configures shortcuts for KDE Plasma 6"
installer_link="-"

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    echo "set Window Maximize = Meta+Shift+Up"
    prev_maximize=$(kreadconfig6 --file kglobalshortcutsrc --group kwin --key "Window Maximize")
    kwriteconfig6 --file kglobalshortcutsrc --group kwin --key "Window Maximize" "Meta+Shift+Up,Meta+PgUp,Maximize Window"
    after_maximize=$(kreadconfig6 --file kglobalshortcutsrc --group kwin --key "Window Maximize")
    echo "prev: ${prev_maximize}"
    echo "after: ${after_maximize}"

    echo "set org.kde.krunner.desktop _launch = Search; Alt+F2"
    prev_krunner=$(kreadconfig6 --file kglobalshortcutsrc --group services --group org.kde.krunner.desktop --key _launch)
    kwriteconfig6 --file kglobalshortcutsrc --group services --group org.kde.krunner.desktop --key _launch "$(printf "Alt+F2\tSearch\t")"
    after_krunner=$(kreadconfig6 --file kglobalshortcutsrc --group services --group org.kde.krunner.desktop --key _launch)

    echo "prev: ${prev_krunner}"
    echo "after: ${after_krunner}"
    
    echo "set ghostty +new-window = Alt+Space"
    create_desktop_file_shortcut "ghosttynewwindow" "ghostty +new-window" "Alt+Space"

    echo "log out and back in for changes to take effect (run slogout)!"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_can_upgrade() {
    return 1
}

inst_upgrade() {
    return 0
}

inst_uninstall() {
    return 0
}

create_desktop_file_shortcut() {
    argname="${1}"
    argexec="${2}"
    argshortcut="${3}"
    
    desktopfile="net.local.${argname}.desktop"
    outfile="${HOME}/.local/share/applications/${desktopfile}"

    if [ -f "${outfile}" ]; then
	outfile_bak="${outfile}.$(date +%Y%m%d_%H%M%S).bak"
        echo "already exist ${outfile}"
        echo "moving to ${outfile_bak}"
	mv ${outfile} ${outfile_bak}
    fi
    echo "[Desktop Entry]" >> ${outfile}
    echo "Exec=${argexec}" >> ${outfile}
    echo "Name=${argname}" >> ${outfile}
    echo "NoDisplay=true" >> ${outfile}
    echo "StartupNotify=false" >> ${outfile}
    echo "Type=Application" >> ${outfile}
    echo "X-KDE-GlobalAccel-CommandShortcut=true" >> ${outfile}
    before_write=$(kreadconfig6 --file kglobalshortcutsrc --group services --group ${desktopfile} --key _launch)
    kwriteconfig6 --file kglobalshortcutsrc --group services --group ${desktopfile} --key _launch "${argshortcut}"
    after_write=$(kreadconfig6 --file kglobalshortcutsrc --group services --group ${desktopfile} --key _launch)

    echo "wrote to kglobalshortcutsrc services ${desktopfile}"
    echo "before: ${before_write}"
    echo "after: ${after_write}"

    return 0
}

