#!/bin/sh

installer_name="ghostty"
installer_description="Installs ghostty and copies config file."
installer_link="https://archlinux.org/packages/extra/x86_64/ghostty/"

pacman_pkg="extra/ghostty"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "List built in ghostty themes"
    htext "ls -l /usr/share/ghostty/themes"
    hseealso
    htext "${installer_link}"
    htext "See install_kdeshortcuts"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

handle_theme() {
    arg_name="${1}"

    dir_theme_dst="${HOME}/.config/ghostty/themes"
    mkdir -p "${dir_theme_dst}"

    file_theme_src="config/${arg_name}"

    if [ ! -f "${file_theme_src}" ]; then
        bold_red "missing ghostty theme file ${file_theme_src}"
        return 1
    fi

    file_theme_dst="${dir_theme_dst}/${arg_name}"
    mv_bak "${file_theme_dst}"
    cp -v "${file_theme_src}" "${file_theme_dst}"

    return 0
}


inst_install() {
    pacman_install "${pacman_pkg}"

    handle_theme "ghostty-lw-light.theme"
    handle_theme "ghostty-lw-mac.theme"

    file_config="${HOME}/.config/ghostty/config"

    mv_bak "${file_config}"
    cp -v config/ghostty.config "${file_config}"

    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
