#!/bin/bash

# Docs
# usage:
#   1. compress a file
#   xz --keep file.tar
#
#   2. uncompress a file
#   xz --keep -d file.tar.xz

installer_name="xz"
installer_description="installs xz"
installer_link="https://archlinux.org/packages/core/x86_64/xz/"

SHORT_PKG="xz"
LONG_PKG="core/${SHORT_PKG}"

inst_is_installed() {
    is_pacman_installed ${SHORT_PKG}
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install ${LONG_PKG}
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_can_upgrade() {
    return 1
}

inst_upgrade() {
    return 1
}

inst_uninstall() {
    pacman_uninstall ${SHORT_PKG}
}

