#!/bin/sh

installer_name="jdtls"
installer_description="Installs jdtls, LSP for java."
installer_link="https://aur.archlinux.org/packages/jdtls"

pacman_pkg="jdtls"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "jdtls --help"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    if is_aur_reinstall; then
        return 1
    fi

    is_command jdtls
}

inst_can_install() {
    if ! is_command git; then
        echo "missing git"
        return 1
    fi

    return 0
}

inst_install() {
    aur_install jdtls

    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
