#!/bin/bash

installer_name="bashrc"
installer_description="Copies bashrc and bash_profile into ${HOME}."
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    cp config/bashrc "${HOME}/.bashrc"
    cp config/bash_profile "${HOME}/.bash_profile"

    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    return 0
}
