#!/bin/bash

installer_name="java17"
installer_description="Installs java 17."
installer_link="https://archlinux.org/packages/extra/x86_64/jdk17-openjdk/"

pacman_pkg="extra/jdk17-openjdk"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Switching versions help"
    htext "archlinux-java --help"
    hseealso
    htext "${installer_link}"
    htext "Main javadoc for arch"
    htext "https://wiki.archlinux.org/title/Java"
}

inst_is_installed() {
    is_pacman_installed ${pacman_pkg}
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install ${pacman_pkg}
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall ${pacman_pkg}
}
