#!/bin/sh

installer_name="strace"
installer_description="Installs strace. Used to monitor app system calls."
installer_link="https://archlinux.org/packages/extra/x86_64/strace/"

pacman_pkg="extra/strace"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "strace COMMAND"
    hexamples
    htext "See which files a program opens"
    htext "strace -e trace=openat,open uptime"
    htext
    hseealso
    htext "${installer_link}"
    htext
    htext "https://peteris.rocks/blog/htop/"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
