#!/bin/sh
set -e
set -u

installer_name="zip"
installer_description="Installs zip."
installer_link="https://archlinux.org/packages/extra/x86_64/zip/"

pacman_pkg="extra/zip"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Compress a file"
    htext "zip file.tar.zip file.tar"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
