#!/bin/sh

installer_name="linuxgroups"
installer_description="Adds the current user to necessary linux groups."
installer_link=""

# shellcheck disable=SC2034 # SC2034 (warning): pacman_pkg appears unused. Verify use (or export if used externally).
pacman_pkg=""

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    return 0
}
