#!/bin/bash

installer_name="docs_keybinds_nvim"
installer_description="Neovim keybindings documentation."
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Search for files"
    htext "<leader>sf"
    htext "<leader>sF"
    htext
    htext "Open splits"
    htext "<C-w>s"
    htext "<C-w>v"
    htext
    htext "Scroll screen top, center, bottom respecting vim.o.scrolloff"
    htext "zt"
    htext "zz"
    htext "zb"
    htext
    htext "Scroll screen down and up"
    htext "<C-e>"
    htext "<C-y>"
    htext
    htext "LSP code actions like import a class or generate toString"
    htext "gra"
    htext
    htext "LSP rename symbol"
    htext "grn"
    htext
    htext "LSP hover"
    htext "grh"
    htext
    htext "LSP symbol"
    htext "grs"
    htext
    htext "Select a code snippet"
    htext "<leader>fs"
    htext
    htext "Comment code lines (vim-commentary built into core)"
    htext ":set commentstring?"
    htext "gcc"
    htext "gc{motion}"
    htext "gc5j"
    htext
    htext "Close a buffer that works well with nvim-tree and keeps window"
    htext "<leader>bd"
    htext
    htext "Search keybindings"
    htext "<leader>sk"
    htext
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    return 0
}
