#!/bin/sh

installer_name="calibre"
installer_description="Installs calibre."
installer_link="https://archlinux.org/packages/extra/x86_64/calibre/"

pacman_pkg="extra/calibre"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "calibre -h"
    hexamples
    htext "Convert an epub to azw3"
    htext "ebook-convert file.epub file.azw3"
    htext
    htext "Get help for a given conversion"
    htext "ebook-convert FILE_FROM FILE_TO -h"
    hseealso
    htext "${installer_link}"
    htext
    htext "Command Line Interface"
    htext "https://manual.calibre-ebook.com/generated/en/cli-index.html"
    htext
    htext "Calibre GitHub repository"
    htext "https://github.com/kovidgoyal/calibre"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

install_calibre_config_db() {
    file_calibre_config="${HOME}/.config/calibre/global.py.json"

    if [ ! -f "${file_calibre_config}" ]; then
        bold_red "file ${file_calibre_config} does not exist"
        return 1
    fi

    file_src_db="${HOME}/library1.db"
    dir_dest_db="${HOME}/.local/share/calibre"
    file_dest_db="${dir_dest_db}/library1.db"

    # Adding lib to allow using gui to store the books there
    mkdir -p "${dir_dest_db}/lib"


    if [ -f "${file_src_db}" ]; then
        bold_yellow "file ${file_src_db} exist consider moving it to ${file_dest_db}"
    fi

    if [ -d "${file_src_db}" ]; then
        bold_yellow "dir ${file_src_db} exist consider moving it to ${file_dest_db}"
    fi

    already_modified_res="$(grep "${file_dest_db}" "${file_calibre_config}")"
    if [ "${already_modified_res}" != "" ]; then
        return 0
    fi

    dry_run_res="$(sed -n "s|${file_src_db}|${file_dest_db}|p" "${file_calibre_config}")"

    if [ "${dry_run_res}" = "" ]; then
        bold_red "failed to find ${file_src_db} in ${file_calibre_config}"
        return 1
    fi

    cp_bak "${file_calibre_config}"
    sed -i "s|${file_src_db}|${file_dest_db}|" "${file_calibre_config}"

    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"

    install_calibre_config_db
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
