#!/bin/bash
# https://aur.archlinux.org/packages/brave-bin
# https://www.youtube.com/watch?v=ttZKwrR6xKQ

echo "creating aur-builds directory..."
mkdir ~/aur-builds
cd ~/aur-builds
echo "cloning repository..."
git clone https://aur.archlinux.org/brave-bin.git
cd brave-bin

echo "building and installing brave-bin..."
makepkg --noconfirm -si

echo "deleting brave-bin folder..."
rm -rf ~/aur-builds/brave-bin

echo "setting default browser..."

declare BRAVE_BROWSER="brave-browser.desktop"
kwriteconfig6 --file kdeglobals --group General --key BrowserApplication "${BRAVE_BROWSER}"
kwriteconfig6 --file kdeglobals --group General --key Http "${BRAVE_BROWSER}"
kwriteconfig6 --file kdeglobals --group General --key Https "${BRAVE_BROWSER}"

echo "next manual installation steps:"
echo "1. sync setup: settings > sync > I have a Sync Code"
echo "2. ..."
