#!/bin/sh

htitle() {
    printf "%25s%s\n" "" "${1:-}"
}

hdesc() {
    printf "\nDESCRIPTION\n"
}

husage() {
    printf "\nUSAGE\n"
}

hexamples() {
    printf "\nEXAMPLES\n"
}

hseealso() {
    printf "\nSEE ALSO\n"
}

htext() {
    printf "%4s%s\n" "" "${1:-}"
}

bold_red() {
    printf "\033[1;38;2;213;78;83m%s\033[0m\n" "${1:-}"
}

bold_yellow() {
    printf "\033[1;38;2;240;198;116m%s\033[0m\n" "${1:-}"
}

is_command() {
    arg_cmd="${1}"

    if command -v "${arg_cmd}" >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

cp_bak() {
    arg_file="${1}"

    if [ ! -f "${arg_file}" ]; then
        return 0
    fi

    file_dir="$(dirname "${arg_file}")"
    file_name="$(basename "${arg_file}")"
    curr_dir="$(realpath .)"

    bak_dir="${curr_dir}/bak${file_dir}"
    bak_file="${file_name}.$(date +%Y%m%d_%H%M%S).bak"

    mkdir -p "${bak_dir}"
    cp -v "${arg_file}" "${bak_dir}/${bak_file}"

    return 0
}

mv_bak() {
    arg_file="${1}"

    if [ ! -f "${arg_file}" ]; then
        return 0
    fi

    file_dir="$(dirname "${arg_file}")"
    file_name="$(basename "${arg_file}")"
    curr_dir="$(realpath .)"

    bak_dir="${curr_dir}/bak${file_dir}"
    bak_file="${file_name}.$(date +%Y%m%d_%H%M%S).bak"

    mkdir -p "${bak_dir}"
    mv -v "${arg_file}" "${bak_dir}/${bak_file}"

    return 0
}

enable_start_service() {
    arg_service="${1}"

    enabled_status="$(systemctl is-enabled "${arg_service}")"
    if [ "${enabled_status}" = "disabled" ]; then
        echo "sudo systemctl enable ${arg_service}"
        sudo systemctl enable "${arg_service}"
    fi

    # active | inactive
    active_status="$(systemctl is-active "${arg_service}")"
    if [ "${active_status}" = "inactive" ]; then
        echo "sudo systemctl start ${arg_service}"
        sudo systemctl start "${arg_service}"
    fi

    return 0
}

ensure_group() {
    arg_group="${1}"

    group_exist="$(awk -F ":" '{print $1}' /etc/group | grep -x "${arg_group}")"

    if [ "${group_exist}" = "" ]; then
        bold_red "group '${arg_group}' does not exist"
        return 1
    fi

    group_member="$(groups | tr " " "\n" | grep "${arg_group}")"

    if [ "${group_member}" != "" ]; then
        echo "user ${USER} already belongs to ${arg_group}"
        return 0
    fi

    echo "adding ${USER} to ${arg_group}"
    sudo usermod -aG "${arg_group}" "${USER}"

    echo "remember to log out or reboot for changes to take effect!"
}

long_to_short_pkg() {
    arg_string="${1}"
    split_last="$(echo "${arg_string}" | tr "/" "\n" | tail -n 1)"
    echo "${split_last}"
}

is_pacman_installed() {
    arg_pkg="${1}"

    short_pkg="$(long_to_short_pkg "${arg_pkg}")"
    if pacman -Qe "${short_pkg}" >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

pacman_install() {
    arg_pkg="${1}"

    # shellcheck disable=SC2310 # SC2310 (info): This function is invoked in an 'if' condition so set -e will be disabled. Invoke separately if failures should cause the script to exit.
    if ! is_command pacman; then
        echo "pacman does not exist"
        exit 1
    fi

    short_pkg="$(long_to_short_pkg "${arg_pkg}")"

    if pacman -Qd "${short_pkg}" 1>/dev/null 2>&1; then
        echo "marking dependency as explicitly installed: ${arg_pkg} - ${short_pkg}"
        sudo pacman -D --asexplicit "${short_pkg}"
        return 0
    fi

    # shellcheck disable=SC2310 # SC2310 (info): This function is invoked in an 'if' condition so set -e will be disabled. Invoke separately if failures should cause the script to exit.
    if is_pacman_installed "${short_pkg}"; then
        return 0
    fi

    echo "installing: ${arg_pkg} - ${short_pkg}"

    sudo pacman --noconfirm -S "${arg_pkg}"
}

pacman_uninstall() {
    arg_pkg="${1}"

    # shellcheck disable=SC2310 # SC2310 (info): This function is invoked in an 'if' condition so set -e will be disabled. Invoke separately if failures should cause the script to exit.
    if ! is_command pacman; then
        echo "pacman does not exist"
        exit 1
    fi

    short_pkg="$(long_to_short_pkg "${arg_pkg}")"

    sudo pacman --noconfirm -R "${short_pkg}"
}

aur_install() {
    arg_pkg="${1}"

    aur_build_dir="${HOME}/aur-builds/${arg_pkg}"

    if [ -e "${aur_build_dir}" ]; then
        if [ ! -d "${aur_build_dir}" ]; then
            bold_red "aborting, not a directory '${aur_build_dir}'"
            return 1
        fi

        if [ ! -d "${aur_build_dir}/.git" ]; then
            bold_red "aborting, not a git repository '${aur_build_dir}'"
            return 1
        fi

        echo "rm -rf \"${aur_build_dir}\""
        rm -rf "${aur_build_dir}"
    fi

    git clone "https://aur.archlinux.org/${arg_pkg}.git" "${aur_build_dir}"

    makepkg --noconfirm -si --dir "${aur_build_dir}"

    return 0
}
