#!/bin/sh

installer_name="stylua"
installer_description="Installs stylua."
installer_link="https://archlinux.org/packages/extra/x86_64/stylua/"

pacman_pkg="extra/stylua"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "stylua --help"
    hexamples
    htext "Format a file using a config file to stdout"
    htext "stylua --config-path stylua.toml - < file.lua"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
