#!/bin/bash

echo "Hello world";

results_array=()
results_array+=(one)
results_array[2]=three
echo "count: ${#results_array[@]}"

for i in "${!results_array[@]}"; do
    printf 'elem %d: %s\n' "$i" "${results_array[$i]}"
done

# install_less
# install_vim
# install_wallpaper
# install_base_devel
# install_brave_bin


# sensitive information:
# install_git: personal data
# install_brave_bin: sync code

exit 0;
