#!/bin/bash

if [[ "${1}" == "" ]]; then
    echo "missing mail"
    exit 1
fi


if [[ "${1}" == "" ]]; then
    echo "missing name"
    exit 1
fi

git config --global user.email "${1}"
git config --global user.name "${2}"

