#!/bin/sh
set -e
set -u

installer_name="gcc"
installer_description="Installs gcc."
installer_link="https://archlinux.org/packages/core/x86_64/gcc/"

pacman_pkg="core/gcc"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Compile with all warnings for a specific standard"
    htext "gcc -Wall -Werror -Wpedantic -std=c99 FILE"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    is_pacman_installed "${pacman_pkg}"
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
