#!/bin/bash

# Docs
# usage:
#   1. uncompress a file
#   unzip file.tar.zip file.tar

installer_name="unzip"
installer_description="installs unzip"
installer_link="https://archlinux.org/packages/extra/x86_64/unzip/"

SHORT_PKG="unzip"
LONG_PKG="extra/${SHORT_PKG}"

inst_is_installed() {
    is_pacman_installed ${SHORT_PKG} 
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install ${LONG_PKG}
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_can_upgrade() {
    return 1
}

inst_upgrade() {
    return 0
}

inst_uninstall() {
    pacman_uninstall ${SHORT_PKG}
}

