#!/bin/sh

installer_name="docs_grep"
installer_description="Documentation for grep."
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Find recursively files matching extension"
    htext "grep -rn --include='*.java' 'new ArrayList<>()' ."
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    return 0
}
