#!/bin/bash

# Docs
# 1. Sensitive information in install_git

readonly PROG_PATH=${0}
readonly PROG_DIR=${0%/*}
readonly FULL_PATH=$(realpath ${PROG_PATH})
readonly FULL_DIR=$(dirname ${FULL_PATH})
readonly PROG_NAME=$(basename $0)

readonly INSTALLERS=(
  "install_less"
  "install_vim"
#  "install_git"
  "install_basedevel"
  "install_brave"
  "install_archwallpaper"
  "install_xorgxev"
  "install_evtest"
  "install_mandb"
  "install_manpages"
  "install_ghostty"
  "install_bashrc"
  "install_kdeshortcuts"
  "install_libinputtools"
  "install_kdesettings"
  "install_shellcheck"
  "install_jq"
  "install_tokei"
  "install_slack"
  "install_java17"
  "install_maven"
  "install_qpdf"
  "install_wlclipboard"
  "install_fd"
  "install_zip"
  "install_unzip"
  "install_nvim"
)

readonly ARG=${1}
readonly OPT1=${2}

source installer_lib

if [[ "${ARG}" == "install" ]]; then
    if [[ "${OPT1}" != "false" ]]; then
        pacman_upgrade
    fi

    for i in "${!INSTALLERS[@]}"; do
        source_installer "${INSTALLERS[$i]}"
        describe_installer

        if inst_is_installed; then
            echo "skipping already installed"
        elif inst_can_install; then
            inst_install

            if [[ $? -ne 0 ]]; then
                echo "failed"
                exit 1
            fi
        else
            echo "skipping cant install"
        fi
    done

    for i in "${!INSTALLERS[@]}"; do
        source_installer "${INSTALLERS[$i]}"

        if inst_can_install_manual; then
            echo -e "\033[1m${installer_name}\033[0m - manual installation steps"
            inst_install_manual
        fi
    done

    exit 0
fi

if [[ "${ARG}" == "upgrade" ]]; then
    pacman_upgrade

    for i in "${!INSTALLERS[@]}"; do
        source_installer "${INSTALLERS[$i]}"

        if inst_is_installed; then
            if ! inst_can_upgrade; then
                continue
            fi

            describe_installer

            inst_upgrade

            if [[ $? -ne 0 ]]; then
                echo "failed ${prog_inst_name}"
                exit 1
            else
                echo "success ${prog_inst_name}"
            fi
        else
            echo "skipping not installed ${prog_inst_name}"
        fi
    done
fi

if [[ "${ARG}" == "uninstall" ]]; then
    pacman_upgrade

    for i in "${!INSTALLERS[@]}"; do
        source_installer "${INSTALLERS[$i]}"

        if inst_is_installed; then
            describe_installer

            inst_uninstall

            if [[ $? -ne 0 ]]; then
                echo "failed ${prog_inst_name}"
                exit 1
            else
                echo "success ${prog_inst_name}"
            fi
        else
            echo "skipping not installed ${prog_inst_name}"
        fi
    done
fi

if [[ "${ARG}" == "docs" ]]; then
    grep "#" install_* \
    | grep -v "bin/bash" \
    | tr -d "#" \
    | column --table -s ":" -C "name=INSTALL FILE,width=25,strictwidth" -C "name=DOCUMENTATION" -l 2 \
    | less
fi
