#!/bin/sh

installer_name="docs"
installer_description="Just documentation."
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Delete # characters"
    htext 'echo "H#e##ll#o W###orld#" | tr -d "#"'
    htext
    htext "Create two columns using colon as separtor"
    htext 'echo "v1:v2" | column --table -s ":" -C "name=INSTALL FILE,width=25,strictwidth" -C "name=DOCUMENTATION" -l 2'
    htext
    htext "Clean up journalctl logs"
    htext "sudo journalctl --vacuum-time=7d"
    htext
    htext "Clean up pacman cache (dry run first)"
    htext "paccache -dk1"
    htext "paccache -rk1"
    htext
    htext "Reset monitor configuration for KDE plasma 6"
    htext "rm ~/.config/kwinoutputconfig.json"
    htext
    htext "Search for WiFi using NetworkManager"
    htext "nmcli device wifi list --rescan yes"
    htext
    htext "Connect to Wifi using NetworkManager"
    htext "nmcli device wifi connect SSID password <PASSWORD>"
    htext
    htext "Open WiFi captive portal"
    htext "http://neverssl.com"
    htext
    htext "See what is using a mountpoint"
    htext "sudo fuser -vm /mnt/usb1"
    htext
    htext "Release notes and news related to systemd"
    htext "less /usr/share/doc/systemd/NEWS"
    htext
    htext "Send a desktop notification"
    htext "notify-send \"Title\" \"Hello World\!\" -a \"my-application\" -t 5000"
    htext
    htext "POSIX man pages for a utility"
    htext "man 1p grep"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    return 0
}
