#!/bin/sh
set -e
set -u

installer_name="feh"
installer_description="Installs feh an image viewer."
installer_link="https://archlinux.org/packages/extra/x86_64/feh/"

pacman_pkg="extra/feh"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Open folder centered on 1920x1080 scaled down to 1280x720"
    htext "feh --geometry 1280x720+320+180 -."
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
