#!/bin/bash

installer_name="maven"
installer_description="installs maven"
installer_link="https://archlinux.org/packages/extra/any/maven/"

SHORT_PKG="maven"
LONG_PKG="extra/${SHORT_PKG}"

inst_is_installed() {
    is_pacman_installed ${SHORT_PKG} 
}

inst_can_install() {
    if ! is_command "java"; then
        return 1
    fi

    return 0
}

inst_install() {
    pacman_install ${LONG_PKG}
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_can_upgrade() {
    return 1
}

inst_upgrade() {
    return 0
}

inst_uninstall() {
    pacman_uninstall ${SHORT_PKG}
}

