#!/bin/sh
set -e
set -u

installer_name="dbeaver"
installer_description="Installs dbeaver."
installer_link="https://archlinux.org/packages/extra/x86_64/dbeaver/"

pacman_pkg="extra/dbeaver"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "dbeaver"
    hexamples
    htext "-"
    hseealso
    htext "${installer_link}"
    htext "https://wiki.archlinux.org/title/Dbeaver"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
