#!/bin/sh
set -e
set -u

installer_name="docs_keybinds_arch"
installer_description="Arch keybindings documentation."
installer_link="-"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "-"
    hexamples
    htext "Toggle fullscreen windowed"
    htext "<M-S-Up>"
    htext
    htext "Resize to tile"
    htext "<M-Up>"
    htext "<M-Down>"
    htext "<M-Left>"
    htext "<M-Right>"
    htext
    htext "Toggle language"
    htext "<A-S>"
    htext
    htext "Open ghostty"
    htext "<A-Space>"
    htext
    htext "DESCRIPTION"
    htext "KEYBIND"
    htext
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    return 0
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    return 0
}
