#!/bin/bash

installer_name="mariadbclients"
installer_description="Installs mariadbclients."
installer_link="https://archlinux.org/packages/extra/x86_64/mariadb-clients/"

pacman_pkg="extra/mariadb-clients"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "mariadb --help"
    hexamples
    htext "Connect to db on localhost"
    htext "mariadb -h localhost -P 30010 -u root -phere --ssl=false sakra"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    return 1
}

inst_can_install() {
    return 0
}

inst_install() {
    if ! is_pacman_installed ${pacman_pkg}; then
        pacman_install ${pacman_pkg}
    fi

    local config_file="$HOME/.my.cnf"
    mv_bak "${config_file}"
    echo "[client]" >> "${config_file}"
    echo "init-command=SET SESSION time_zone='+00:00'" >> "${config_file}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 1
}

inst_uninstall() {
    pacman_uninstall ${pacman_pkg}
}
