#!/bin/sh
set -e
set -u

installer_name="fd"
installer_description="Installs fd."
installer_link="https://archlinux.org/packages/extra/x86_64/fd/"

pacman_pkg="extra/fd"

inst_help() {
    htitle "${installer_name}"
    hdesc
    htext "${installer_description}"
    husage
    htext "fd PATTERN [DIR]"
    hexamples
    htext "Find files in /var/log containing pac"
    htext "fd pac /var/log"
    hseealso
    htext "${installer_link}"
}

inst_is_installed() {
    is_pacman_installed "${pacman_pkg}"
}

inst_can_install() {
    return 0
}

inst_install() {
    pacman_install "${pacman_pkg}"
}

inst_can_install_manual() {
    return 1
}

inst_install_manual() {
    return 0
}

inst_uninstall() {
    pacman_uninstall "${pacman_pkg}"
}
