#
# ~/.bash_profile
#

if [ -f ~/.bashrc ]; then
    # shellcheck disable=SC1090 # SC1090 (warning): ShellCheck can't follow non-constant source. Use a directive to specify location.
    . ~/.bashrc
fi

PATH="${PATH}:${HOME}/bin"
PATH="${PATH}:${HOME}/bin/scripts"
