" .vimrc

" show current line number and relative to it
set number
set relativenumber

" disable mouse to allow right click through terminal for copy/paste
set mouse=

set hlsearch

"This unsets the last search pattern register by hitting return
nnoremap <CR> :noh<CR><CR>

set tabstop=4
set softtabstop=4
set smartindent
set shiftwidth=4
set cmdheight=1
set breakindent

